name: foodie_restaurant
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.0.0
  circular_profile_avatar: ^1.0.6
  google_maps_flutter: ^0.5.0
  geolocator: ^5.3.0
  # scoped model
  scoped_model: ^1.0.1
  # dependency injection
  get_it: ^1.0.3
  #staggered gridview
  flutter_staggered_grid_view: ^0.3.0
  #font awesome icons and font 
  font_awesome_flutter: ^8.7.0
  #Circuler menu 
  unicorndial: ^1.1.5
  #Vector Math for Radial menu 
  vector_math: ^2.0.8
  #Image Slider
  carousel_slider: ^1.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/chris.jpg
   - assets/images/dressers.png
   - assets/images/wardrobe.png
   - assets/images/sofas.png
   - assets/images/sofad.png
   - assets/images/desks.png
   - assets/images/chair.jpg
   - assets/images/anotherchair.jpg
   - assets/images/ottoman.jpg
   - assets/images/otto2.jpeg
   - assets/images/otto3.jpg
   - assets/images/otto4.jpg
   - assets/images/otto5.jpg
   - assets/images/box.png
   - assets/images/card.png
   - assets/images/truck.png
   - assets/images/trucks.png
   - assets/images/returnbox.png
   - assets/images/facebook.png
   - assets/images/in.png
   - assets/images/googleplus.png
   - assets/images/twitter.jpg
   - assets/images/chat.png
   - assets/images/inquiry_page_bg.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
